### PR TITLE
target wasm + update various dependencies

### PR DESCRIPTION
**Pull request by joreilly**
Screenshot 2024-02-25 at 17 02 31

Addresses https://github.com/overpas/compose-treemap-chart/issues/98

---

## PR-Codex overview
The focus of this PR is to add support for WebAssembly (Wasm) in the project by including the necessary configurations, dependencies, and resources.

### Detailed summary
- Added `web-wasm` module
- Configured Detekt to exclude generated files
- Updated Kotlin and Compose versions
- Implemented Wasm support in `sample`, `shared`, and `web-wasm` modules
- Added Wasm-specific resources and code in `web-wasm` module

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by joreilly** [comment]
Some at least of build failures are due to dependency versions in sample not being updated....will look at that now.

@overpas can you approve workflow again

**Comment by overpas** [comment]
@joreilly Also, if it's not too much trouble, could you add a wasm sample under /sample directory?

**Comment by joreilly** [comment]
@overpas I'm getting out of memory errors in macrobenchmark tests for some reason (https://github.com/overpas/compose-treemap-chart/actions/runs/8040826349/job/21959371678?pr=99) .....just in case you've come across this?

**Comment by overpas** [comment]
> @overpas I'm getting out of memory errors in macrobenchmark tests for some reason (https://github.com/overpas/compose-treemap-chart/actions/runs/8040826349/job/21959371678?pr=99) .....just in case you've come across this?

No idea. If its only macrobenchmark that fails, we can skip it, I guess

**Comment by joreilly** [comment]
>Also, if it's not too much trouble, could you add a wasm sample under /sample directory?

At point where just need to create actuals for `formatPercentage` and `formatDollarAmount` ...will take a look at those tomorrow hopefully

**Comment by joreilly** [comment]
@overpas wasm sample added now

Screenshot 2024-02-26 at 12 26 00

**Comment by overpas** [comment]
Just need to fix detekt issues and let's merge, I'll do something with macrobenchmark later

**Comment by joreilly** [comment]
pushed detekt fixes

**Comment by joreilly** [comment]
hmm, still another error that I missed here...looks to be in generated code....

```
/home/runner/work/compose-treemap-chart/compose-treemap-chart/sample/web-wasm/build/generated/compose/resourceGenerator/kotlin/compose_treemap_chart/sample/web-wasm/generated/resources/Res.kt:6:1: Package name should match the pattern: [a-z]+(\.[a-z][A-Za-z0-9]*)* [PackageNaming]
```

**Comment by overpas** [comment]
> hmm, still another error that I missed here...looks to be in generated code....
> 
> ```
> /home/runner/work/compose-treemap-chart/compose-treemap-chart/sample/web-wasm/build/generated/compose/resourceGenerator/kotlin/compose_treemap_chart/sample/web-wasm/generated/resources/Res.kt:6:1: Package name should match the pattern: [a-z]+(\.[a-z][A-Za-z0-9]*)* [PackageNaming]
> ```

You can add
```yaml
    excludes:
      - '**/generated/**'
```
to `PackageNaming` rule in [detekt config](https://github.com/overpas/compose-treemap-chart/blob/master/config/detekt/detekt.yml)

**Pull request merged**
